---
- name: Create slave home directory
  ansible.windows.win_file:
    path: '{{ slave_windows_workdir }}'
    state: directory

- name: Download slave.jar from master
  ansible.windows.win_get_url:
    url: '{{ master_url }}/jnlpJars/slave.jar'
    dest: '{{ slave_windows_workdir }}/slave.jar'
    force: false

- ansible.builtin.import_tasks: agent.yml

- ansible.builtin.import_tasks: service.yml
...
